#!/usr/bin/env python3
from __future__ import annotations

import argparse
import cmath
import itertools
import json
import tarfile
from pathlib import Path
from typing import Any

import numpy as np
import sympy as sp

from . import runtime_bridge as bridge


ROOT = Path(__file__).resolve().parents[2] / "common"
GROUP_NUMBER = "10.4.1.31"
PACKAGE_NAME = "review_package_10.4.1.31_ai_expanded"
PACKAGE_DIR = ROOT / PACKAGE_NAME
PACKAGE_TARBALL = ROOT / f"{PACKAGE_NAME}.tar.gz"

LOCAL_REP_CENSUS_AUDIT_MD = ROOT / "single_group_local_rep_census_audit.md"
LOCAL_REP_CENSUS_SUMMARY_JSON = ROOT / "single_group_local_rep_census_summary.json"
AI_EXPANDED_CANDIDATES_JSON = ROOT / "single_group_ai_expanded_candidates.json"
AI_EXPANDED_MATRIX_JSON = ROOT / "single_group_ai_expanded_matrix.json"
AI_EXPANDED_BASIS_JSON = ROOT / "single_group_ai_expanded_basis.json"
BS_VS_AI_EXPANDED_SUMMARY_JSON = ROOT / "single_group_bs_vs_ai_expanded_summary.json"

MANIFOLDS = ["P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "S1", "S2"]
TRUSTED_FAMILIES = ["o", "n", "m", "l", "k", "j", "i", "h", "g", "f", "e", "d", "c", "b", "a"]
INCLUDED_FAMILIES = ["o", "m", "k", "l", "c", "f"]
TIER_2_FAMILIES = ["h", "g", "e", "d", "b", "a"]
TIER_3_FAMILIES = ["n", "j", "i"]

LOCAL_REP_LIBRARY: dict[str, list[dict[str, Any]]] = {
    "o": [
        {
            "id": "o_A",
            "label": "A",
            "dimension": 1,
            "site_symmetry": "1",
            "local_rep_scope": "full magnetic",
            "definition": "Unique one-dimensional character of the trivial site-symmetry group.",
            "character_on_unitary_stabilizer": {"0": 1},
        }
    ],
    "m": [
        {
            "id": "m_A_prime",
            "label": "A'",
            "dimension": 1,
            "site_symmetry": "m",
            "local_rep_scope": "full magnetic",
            "definition": "Mirror-even one-dimensional character on the unitary order-2 site symmetry.",
            "character_on_unitary_stabilizer": {"0": 1, "7": 1},
        },
        {
            "id": "m_A_double_prime",
            "label": "A''",
            "dimension": 1,
            "site_symmetry": "m",
            "local_rep_scope": "full magnetic",
            "definition": "Mirror-odd one-dimensional character on the unitary order-2 site symmetry.",
            "character_on_unitary_stabilizer": {"0": 1, "7": -1},
        },
    ],
    "k": [
        {
            "id": "k_A",
            "label": "A",
            "dimension": 1,
            "site_symmetry": "2",
            "local_rep_scope": "full magnetic",
            "definition": "C2-even one-dimensional character on the unitary order-2 site symmetry.",
            "character_on_unitary_stabilizer": {"0": 1, "3": 1},
        },
        {
            "id": "k_B",
            "label": "B",
            "dimension": 1,
            "site_symmetry": "2",
            "local_rep_scope": "full magnetic",
            "definition": "C2-odd one-dimensional character on the unitary order-2 site symmetry.",
            "character_on_unitary_stabilizer": {"0": 1, "3": -1},
        },
    ],
    "l": [
        {
            "id": "l_A",
            "label": "A",
            "dimension": 1,
            "site_symmetry": "2",
            "local_rep_scope": "full magnetic",
            "definition": "C2-even one-dimensional character on the unitary order-2 site symmetry.",
            "character_on_unitary_stabilizer": {"0": 1, "3": 1},
        },
        {
            "id": "l_B",
            "label": "B",
            "dimension": 1,
            "site_symmetry": "2",
            "local_rep_scope": "full magnetic",
            "definition": "C2-odd one-dimensional character on the unitary order-2 site symmetry.",
            "character_on_unitary_stabilizer": {"0": 1, "3": -1},
        },
    ],
    "c": [
        {
            "id": "c_Ag",
            "label": "Ag",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Ag character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": 1, "4": 1, "7": 1},
        },
        {
            "id": "c_Bg",
            "label": "Bg",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Bg character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": -1, "4": 1, "7": -1},
        },
        {
            "id": "c_Au",
            "label": "Au",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Au character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": 1, "4": -1, "7": -1},
        },
        {
            "id": "c_Bu",
            "label": "Bu",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Bu character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": -1, "4": -1, "7": 1},
        },
    ],
    "f": [
        {
            "id": "f_Ag",
            "label": "Ag",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Ag character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": 1, "4": 1, "7": 1},
        },
        {
            "id": "f_Bg",
            "label": "Bg",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Bg character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": -1, "4": 1, "7": -1},
        },
        {
            "id": "f_Au",
            "label": "Au",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Au character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": 1, "4": -1, "7": -1},
        },
        {
            "id": "f_Bu",
            "label": "Bu",
            "dimension": 1,
            "site_symmetry": "2/m",
            "local_rep_scope": "full magnetic",
            "definition": "Bu character on the unitary C2h site symmetry, generated by op 3 (C2) and op 7 (m).",
            "character_on_unitary_stabilizer": {"0": 1, "3": -1, "4": -1, "7": 1},
        },
    ],
}

BACKGROUND_CONTEXT = {
    "audit/single_group_ai_bridge_audit.md": ROOT / "single_group_ai_bridge_audit.md",
    "audit/single_group_ai_bridge_summary.json": ROOT / "single_group_ai_bridge_summary.json",
    "audit/single_group_bs_with_planes_summary.json": ROOT / "single_group_bs_with_planes_summary.json",
    "audit/single_group_plane_formalism_audit.md": ROOT / "single_group_plane_formalism_audit.md",
    "audit/single_group_plane_formalism_summary.json": ROOT / "single_group_plane_formalism_summary.json",
    "audit/single_group_site_symmetry_check.json": ROOT / "single_group_site_symmetry_check.json",
    "background/single_group_connectivity.json": ROOT / "single_group_connectivity.json",
    "background/single_group_kmanifolds.json": ROOT / "single_group_kmanifolds.json",
    "basis/single_group_bs_with_planes_basis_pretty.json": ROOT / "single_group_bs_with_planes_basis_pretty.json",
    "basis/single_group_bs_with_planes_basis_raw.json": ROOT / "single_group_bs_with_planes_basis_raw.json",
    "matrix/single_group_full_compatibility_with_planes.json": ROOT / "single_group_full_compatibility_with_planes.json",
    "ai/single_group_ai_min_generators.json": ROOT / "single_group_ai_min_generators.json",
    "ai/single_group_ai_min_matrix.json": ROOT / "single_group_ai_min_matrix.json",
    "ai/single_group_bs_vs_ai_min_summary.json": ROOT / "single_group_bs_vs_ai_min_summary.json",
}


def load_json(path: Path) -> Any:
    return json.loads(path.read_text())


def write_json(path: Path, obj: Any) -> None:
    path.write_text(json.dumps(obj, indent=2, ensure_ascii=True) + "\n")


def write_text(path: Path, text: str) -> None:
    path.write_text(text.rstrip() + "\n")


def raw_ops(ctx: dict[str, Any]) -> list[dict[str, Any]]:
    ops = []
    for index, (rotation, translation, tr) in enumerate(zip(ctx["ssg"].rotC, ctx["ssg"].tauC, ctx["ssg"].time_reversal)):
        ops.append(
            {
                "index": index,
                "rotation": np.array(rotation, dtype=float),
                "translation": np.array(translation, dtype=float),
                "time_reversal": int(tr) < 0,
            }
        )
    return ops


def match_raw_op(ctx: dict[str, Any], operations: list[dict[str, Any]], rotation: np.ndarray, translation: np.ndarray, time_reversal: bool) -> int:
    for op in operations:
        if op["time_reversal"] != time_reversal:
            continue
        if np.linalg.norm(rotation - op["rotation"]) > 1e-8:
            continue
        is_lattice, _ = bridge.vector_is_lattice(ctx["supercell"], translation - op["translation"])
        if is_lattice:
            return int(op["index"])
    raise KeyError("no matching raw operation found")


def build_group_tables(ctx: dict[str, Any]) -> dict[str, Any]:
    operations = raw_ops(ctx)

    def compose(index_a: int, index_b: int) -> int:
        op_a = operations[index_a]
        op_b = operations[index_b]
        return match_raw_op(
            ctx,
            operations,
            op_a["rotation"] @ op_b["rotation"],
            op_a["rotation"] @ op_b["translation"] + op_a["translation"],
            bool(op_a["time_reversal"]) ^ bool(op_b["time_reversal"]),
        )

    inverse: dict[int, int] = {}
    for index_a in range(len(operations)):
        for index_b in range(len(operations)):
            if compose(index_a, index_b) == 0 and compose(index_b, index_a) == 0:
                inverse[index_a] = index_b
                break
        if index_a not in inverse:
            raise ValueError(f"failed to find inverse for operation {index_a}")

    return {
        "operations": operations,
        "compose": compose,
        "inverse": inverse,
    }


def sample_point_conventional(entry: dict[str, Any], ctx: dict[str, Any]) -> np.ndarray:
    return ctx["supercell"] @ bridge.representative_sample_point_magnetic(entry)


def orbit_for_sample_entry(entry: dict[str, Any], ctx: dict[str, Any], group_tables: dict[str, Any]) -> list[dict[str, Any]]:
    rep_mag = bridge.representative_sample_point_magnetic(entry)
    rep_conv = ctx["supercell"] @ rep_mag
    orbit: list[dict[str, Any]] = []
    seen = set()
    for op in group_tables["operations"]:
        image_conv = op["rotation"] @ rep_conv + op["translation"]
        key = bridge.reduced_magnetic_key(ctx["supercell"], image_conv)
        if key in seen:
            continue
        seen.add(key)
        orbit.append(
            {
                "source_operation_index": int(op["index"]),
                "time_reversal_source": bool(op["time_reversal"]),
                "magnetic_coordinate": list(key),
                "conventional_coordinate": bridge.format_vector(image_conv),
                "conv_vector": image_conv,
            }
        )
    return orbit


def manifold_global_unitary_indices(ctx: dict[str, Any], group_tables: dict[str, Any]) -> dict[str, list[int]]:
    result: dict[str, list[int]] = {}
    for manifold in MANIFOLDS:
        info = bridge.manifold_linear_characters(manifold, ctx)
        result[manifold] = [
            match_raw_op(ctx, group_tables["operations"], rotation, translation, False)
            for rotation, translation in zip(info["unitary_rotations"], info["unitary_translations"])
        ]
    return result


def family_tier(letter: str) -> str:
    if letter in INCLUDED_FAMILIES:
        return "Tier 1"
    if letter in TIER_2_FAMILIES:
        return "Tier 2"
    return "Tier 3"


def build_local_rep_census(ctx: dict[str, Any]) -> dict[str, Any]:
    entries_by_letter = {entry["letter"]: entry for entry in ctx["wyckoff_entries"]}
    bridge_checks = bridge.validate_bridge_stabilizers(ctx)
    bridge_by_letter = {entry["letter"]: entry for entry in bridge_checks["entries"]}

    tier_records: list[dict[str, Any]] = []
    for letter in TRUSTED_FAMILIES:
        entry = entries_by_letter[letter]
        bridge_entry = bridge_by_letter[letter]
        included_reps = LOCAL_REP_LIBRARY.get(letter, [])

        if letter in INCLUDED_FAMILIES:
            rationale = "Purely unitary site symmetry; all one-dimensional local irreps can be reconstructed directly from the unitary stabilizer."
        elif letter in TIER_2_FAMILIES:
            rationale = "Point-like and double-checked, but the site symmetry contains antiunitary elements; full magnetic local coreps are not yet reconstructed."
        else:
            rationale = "Site symmetry contains antiunitary elements and the family also carries free real-space parameters; defer until a dedicated magnetic corep audit is done."

        tier_records.append(
            {
                "letter": letter,
                "tier": family_tier(letter),
                "dimension": int(entry["dim"]),
                "multiplicity": int(entry["mult"]),
                "representative_coordinate_symbolic": entry["representative_coordinate"],
                "site_symmetry": entry["site_symmetry"],
                "unitary_stabilizer_size": int(bridge_entry["bridge_unitary_count"]),
                "antiunitary_stabilizer_size": int(bridge_entry["bridge_antiunitary_count"]),
                "included_local_rep_ids": [rep["id"] for rep in included_reps],
                "rationale": rationale,
            }
        )

    included_local_reps = {letter: [rep["id"] for rep in LOCAL_REP_LIBRARY.get(letter, [])] for letter in INCLUDED_FAMILIES}
    return {
        "group_number": GROUP_NUMBER,
        "trusted_families": TRUSTED_FAMILIES,
        "included_families": INCLUDED_FAMILIES,
        "excluded_families": TIER_2_FAMILIES + TIER_3_FAMILIES,
        "included_local_reps": included_local_reps,
        "can_build_expanded_ai_candidates": True,
        "next_blocker": "Extend the site-symmetry side from unitary-only local irreps to full magnetic local coreps on the antiunitary families a,b,d,e,g,h,n,i,j.",
        "tiers": tier_records,
        "missing_file_note": "No local swyckoff.py exists in this repository; the real-space side is provided by swyckoff_r.py and the k-space side by swyckoff_k.py.",
    }


def build_local_rep_census_md(census: dict[str, Any], ctx: dict[str, Any]) -> str:
    lines = [
        "# Single-Group Local-Rep Census Audit for 10.4.1.31",
        "",
        "## Scope",
        "",
        "- Group only: `10.4.1.31`.",
        "- Stage: expand the atomic-side work from the earlier minimal prototype to a larger single-group AI candidate lattice.",
        "- This audit keeps the earlier bridge result fixed and only pushes the real-space/local-rep side forward.",
        "",
        "## Code Paths Actually Used",
        "",
        "- `swyckoff_r.py`: real-space families, representative coordinates, sample-point generation, and the audited site-symmetry labels.",
        "- `swyckoff_k.py`: background source of the same standardized operation convention and with-planes unknown ordering context.",
        "- `SSGReps/SSGReps/SSGReps.py`: raw little-group operations plus `character`/`rep_degree`; the `exp(-i k·tauC)` correction remains mandatory.",
        "- `swyckoff.py`: not present in this repository, so it is not part of the actual real-space path for this group.",
        "",
        "## Trusted Families",
        "",
        f"- All previously double-checked families remain trusted at the geometric/site-symmetry level: `{', '.join(census['trusted_families'])}`.",
        "- The bridge `r_conv = P r_mag` with `P = diag(1,2,2)` is reused without modification.",
        "",
        "## Tiering",
        "",
        "- Tier 1: `o, m, k, l, c, f`.",
        "  These six families have purely unitary site symmetry, so their local irreps are fully reconstructable as honest one-dimensional characters of the audited stabilizer.",
        "- Tier 2: `h, g, e, d, b, a`.",
        "  These are point-like and geometrically stable, but the site symmetry contains antiunitary elements; a magnetic-corep audit is still missing.",
        "- Tier 3: `n, j, i`.",
        "  These families combine antiunitary site symmetry with free real-space parameters, so they were left out of this round.",
        "",
        "## Included Local Reps",
        "",
        "- `o`: `o_A`.",
        "- `m`: `m_A_prime`, `m_A_double_prime`.",
        "- `k`: `k_A`, `k_B`.",
        "- `l`: `l_A`, `l_B`.",
        "- `c`: `c_Ag`, `c_Bg`, `c_Au`, `c_Bu`.",
        "- `f`: `f_Ag`, `f_Bg`, `f_Au`, `f_Bu`.",
        "",
        "## Important Sample-Point Detail",
        "",
        "- For parameter families such as `o/m/k/l`, the orbit must be generated from a generic sample point inside the family, not directly from the symbolic `x0` anchor.",
        "- Reusing the old `x0`-based orbit logic would incorrectly collapse these families to more special positions.",
        "- This round therefore uses the same sample-parameter convention as the bridge helper when the family dimension is nonzero.",
        "",
        "## Current Inclusion Boundary",
        "",
        "- Expanded candidate generation is intentionally restricted to the Tier-1 families above.",
        "- The current script does not attempt magnetic Wigner coreps for antiunitary site symmetries, so `a,b,d,e,g,h,n,i,j` stay outside the candidate matrix.",
        "- This means the present `AI_expanded` is larger than the earlier 2-generator prototype, but it is still not the full single-group AI lattice.",
        "",
        "## BS Target Space",
        "",
        f"- The target space remains the audited 31-dimensional with-planes unknown ordering from `single_group_bs_with_planes_basis_raw.json` and `single_group_full_compatibility_with_planes.json`.",
        f"- `rank(BS_with_planes) = {len(ctx['basis_raw']['basis_vectors'])}` at the basis level used here.",
    ]
    return "\n".join(lines)


def induce_candidate(
    entry: dict[str, Any],
    local_rep: dict[str, Any],
    ctx: dict[str, Any],
    group_tables: dict[str, Any],
    manifold_globals: dict[str, list[int]],
) -> dict[str, Any]:
    orbit = orbit_for_sample_entry(entry, ctx, group_tables)
    stabilizer = bridge.bridge_stabilizer_for_entry(entry, ctx)
    stabilizer_unitary = set(stabilizer["unitary_indices"])
    local_character = {int(index): int(value) for index, value in local_rep["character_on_unitary_stabilizer"].items()}

    manifold_multiplicities: dict[str, list[int]] = {}
    manifold_band_characters: dict[str, list[dict[str, float]]] = {}

    for manifold in MANIFOLDS:
        info = bridge.manifold_linear_characters(manifold, ctx)
        band_character: list[complex] = []
        for op_index, rotation, translation in zip(
            manifold_globals[manifold],
            info["unitary_rotations"],
            info["unitary_translations"],
        ):
            total = 0j
            for site in orbit:
                coset_index = int(site["source_operation_index"])
                conj_index = group_tables["compose"](
                    group_tables["inverse"][coset_index],
                    group_tables["compose"](op_index, coset_index),
                )
                if conj_index not in stabilizer_unitary:
                    continue
                point_conv = np.array(site["conv_vector"], dtype=float)
                delta = rotation @ point_conv + translation - point_conv
                fixed, _ = bridge.vector_is_lattice(ctx["supercell"], delta)
                if not fixed:
                    continue
                total += local_character[conj_index] * cmath.exp(-1j * float(np.dot(info["kconv"], delta)))
            band_character.append(total)

        chars = info["linear_characters"]
        band = np.array(band_character, dtype=complex)
        gram = chars @ chars.conj().T / chars.shape[1]
        rhs = chars.conj() @ band / chars.shape[1]
        multiplicities = np.linalg.solve(gram, rhs)
        if not np.allclose(multiplicities, np.rint(multiplicities.real), atol=1e-8):
            raise ValueError(f"{local_rep['id']} on {manifold}: multiplicities are not integral")

        multiplicities_round = [int(round(float(value.real))) for value in multiplicities]
        recon = np.array(multiplicities_round, dtype=complex) @ chars
        if not np.allclose(recon, band, atol=1e-8):
            raise ValueError(f"{local_rep['id']} on {manifold}: character reconstruction failed")

        manifold_multiplicities[manifold] = multiplicities_round
        manifold_band_characters[manifold] = [
            {"real": round(value.real, 12), "imag": round(value.imag, 12)} for value in band_character
        ]

    unknown_vector: list[int] = []
    for token in ctx["basis_raw"]["unknown_ordering"]:
        manifold, rep_index_str = token.split("_R")
        unknown_vector.append(manifold_multiplicities[manifold][int(rep_index_str) - 1])

    compatibility = sp.Matrix(ctx["compat"]["global_matrix"]) * sp.Matrix(unknown_vector)
    compatibility_zero = all(int(value) == 0 for value in list(compatibility))

    basis_matrix = sp.Matrix.hstack(*[sp.Matrix(column["vector"]) for column in ctx["basis_raw"]["basis_vectors"]])
    coeff_solution = basis_matrix.gauss_jordan_solve(sp.Matrix(unknown_vector))[0]
    coeffs = [int(value) for value in coeff_solution]

    sample_mag = bridge.representative_sample_point_magnetic(entry)
    sample_conv = sample_point_conventional(entry, ctx)

    return {
        "generator_id": local_rep["id"],
        "family_letter": entry["letter"],
        "family_dimension": int(entry["dim"]),
        "family_tier": family_tier(entry["letter"]),
        "representative_coordinate_symbolic": entry["representative_coordinate"],
        "sample_parameters": bridge.format_vector(bridge.sample_parameters_for_dimension(int(entry["dim"]))),
        "representative_coordinate_magnetic_sample": bridge.format_vector(sample_mag),
        "representative_coordinate_conventional_sample": bridge.format_vector(sample_conv),
        "multiplicity": int(entry["mult"]),
        "sample_orbit_size": len(orbit),
        "site_symmetry": entry["site_symmetry"],
        "stabilizer_summary": {
            "unitary_size": stabilizer["bridge_unitary_count"],
            "antiunitary_size": stabilizer["bridge_antiunitary_count"],
            "unitary_indices": stabilizer["unitary_indices"],
            "antiunitary_indices": stabilizer["antiunitary_indices"],
        },
        "local_rep": {
            "label": local_rep["label"],
            "dimension": local_rep["dimension"],
            "local_rep_scope": local_rep["local_rep_scope"],
            "definition": local_rep["definition"],
            "character_on_unitary_stabilizer": local_rep["character_on_unitary_stabilizer"],
        },
        "orbit": [
            {
                "source_operation_index": site["source_operation_index"],
                "time_reversal_source": site["time_reversal_source"],
                "magnetic_coordinate": site["magnetic_coordinate"],
                "conventional_coordinate": site["conventional_coordinate"],
            }
            for site in orbit
        ],
        "manifold_multiplicities": manifold_multiplicities,
        "manifold_band_characters": manifold_band_characters,
        "unknown_vector": unknown_vector,
        "compatibility_zero": compatibility_zero,
        "bs_basis_coefficients": coeffs,
    }


def build_expanded_candidates(ctx: dict[str, Any]) -> dict[str, Any]:
    group_tables = build_group_tables(ctx)
    manifold_globals = manifold_global_unitary_indices(ctx, group_tables)

    generators: list[dict[str, Any]] = []
    failures: list[dict[str, Any]] = []
    for letter in INCLUDED_FAMILIES:
        entry = next(item for item in ctx["wyckoff_entries"] if item["letter"] == letter)
        for local_rep in LOCAL_REP_LIBRARY[letter]:
            try:
                generators.append(induce_candidate(entry, local_rep, ctx, group_tables, manifold_globals))
            except Exception as exc:  # pragma: no cover - failure path should stay visible in JSON
                failures.append(
                    {
                        "generator_id": local_rep["id"],
                        "family_letter": letter,
                        "error": str(exc),
                    }
                )

    if failures:
        raise ValueError(f"candidate generation unexpectedly failed: {failures}")

    column_order = [generator["generator_id"] for generator in generators]
    a_expanded_columns = [generator["unknown_vector"] for generator in generators]
    coeff_columns = [generator["bs_basis_coefficients"] for generator in generators]
    a_expanded = sp.Matrix.hstack(*[sp.Matrix(column) for column in a_expanded_columns])
    coeff_matrix = sp.Matrix.hstack(*[sp.Matrix(column) for column in coeff_columns])

    return {
        "generators": generators,
        "column_order": column_order,
        "A_expanded_columns": a_expanded_columns,
        "coeff_columns": coeff_columns,
        "rank_z": int(a_expanded.rank()),
        "rank_q": int(a_expanded.rank()),
        "coeff_rank": int(coeff_matrix.rank()),
    }


def choose_integer_basis(expanded: dict[str, Any]) -> dict[str, Any]:
    coefficient_columns = [sp.Matrix(column) for column in expanded["coeff_columns"]]
    full_rank = int(sp.Matrix.hstack(*coefficient_columns).rank())

    chosen_subset: tuple[int, ...] | None = None
    relation_by_id: dict[str, list[int]] = {}
    for subset in itertools.combinations(range(len(coefficient_columns)), full_rank):
        basis_matrix = sp.Matrix.hstack(*[coefficient_columns[index] for index in subset])
        if int(basis_matrix.rank()) != full_rank:
            continue
        current_relations: dict[str, list[int]] = {}
        ok = True
        for generator_id, coeff_column in zip(expanded["column_order"], coefficient_columns):
            solution = basis_matrix.gauss_jordan_solve(coeff_column)[0]
            if any(not value.is_integer for value in solution):
                ok = False
                break
            current_relations[generator_id] = [int(value) for value in solution]
        if ok:
            chosen_subset = subset
            relation_by_id = current_relations
            break

    if chosen_subset is None:
        raise ValueError("failed to find an exact integer subset basis for the expanded candidates")

    basis_ids = [expanded["column_order"][index] for index in chosen_subset]
    basis_vectors = [expanded["A_expanded_columns"][index] for index in chosen_subset]
    basis_coefficients = [expanded["coeff_columns"][index] for index in chosen_subset]

    dependent_ids = [generator_id for generator_id in expanded["column_order"] if generator_id not in basis_ids]
    return {
        "basis_ids": basis_ids,
        "basis_vectors": basis_vectors,
        "basis_coefficients": basis_coefficients,
        "candidate_to_basis_relations": relation_by_id,
        "dependent_ids": dependent_ids,
        "rank_z": len(basis_ids),
    }


def build_bs_vs_ai_expanded_summary(expanded: dict[str, Any], basis: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]:
    bs_rank = len(ctx["basis_raw"]["basis_vectors"])
    ai_min_summary = load_json(ROOT / "single_group_bs_vs_ai_min_summary.json")
    basis_matrix = sp.Matrix.hstack(*[sp.Matrix(column["vector"]) for column in ctx["basis_raw"]["basis_vectors"]])
    expanded_matrix = sp.Matrix.hstack(*[sp.Matrix(column) for column in expanded["A_expanded_columns"]])

    return {
        "group_number": GROUP_NUMBER,
        "rank_BS_with_planes": bs_rank,
        "rank_AI_min": int(ai_min_summary["rank_AI_min"]),
        "rank_AI_expanded": int(expanded["rank_z"]),
        "AI_expanded_in_BS": int(sp.Matrix.hstack(basis_matrix, expanded_matrix).rank()) == bs_rank,
        "rank_span_BS_plus_AI_expanded": int(sp.Matrix.hstack(basis_matrix, expanded_matrix).rank()),
        "raw_candidate_count": len(expanded["column_order"]),
        "basis_generator_ids": basis["basis_ids"],
        "new_independent_directions_vs_min_prototype": int(expanded["rank_z"]) - int(ai_min_summary["rank_AI_min"]),
        "remaining_bs_rank_gap": bs_rank - int(expanded["rank_z"]),
        "new_coverage_statement": "The expanded candidate lattice raises the atomic-side rank from 2 to 6, so it adds 4 independent directions beyond the earlier minimal prototype.",
        "remaining_gap_statement": "The remaining rank-2 gap is consistent with the still-excluded antiunitary families/coreps; this is still not the full single-group AI lattice.",
        "missing_pieces": [
            "full magnetic local coreps on a,b,d,e,g,h",
            "magnetic-corep treatment for the antiunitary parameter families n,i,j",
        ],
        "scope_note": "This remains an expanded single-group AI candidate lattice, not the final BS/AI result and not a final topological classification.",
    }


def build_candidates_json(expanded: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]:
    return {
        "group_number": GROUP_NUMBER,
        "unknown_ordering": ctx["basis_raw"]["unknown_ordering"],
        "candidate_generation_scope": "Only the six purely unitary site-symmetry families o,m,k,l,c,f are included in this round.",
        "generators": expanded["generators"],
    }


def build_matrix_json(expanded: dict[str, Any], basis: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]:
    rows = []
    for index, unknown in enumerate(ctx["basis_raw"]["unknown_ordering"]):
        rows.append(
            {
                "unknown": unknown,
                "coefficients": [column[index] for column in expanded["A_expanded_columns"]],
            }
        )
    return {
        "group_number": GROUP_NUMBER,
        "matrix_orientation": "columns_are_generators",
        "column_order": expanded["column_order"],
        "unknown_ordering": ctx["basis_raw"]["unknown_ordering"],
        "A_expanded_columns": expanded["A_expanded_columns"],
        "A_expanded_rows": rows,
        "A_expanded_bs_coefficients": expanded["coeff_columns"],
        "rank_z": expanded["rank_z"],
        "rank_q": expanded["rank_q"],
        "linearly_dependent_candidate_ids": basis["dependent_ids"],
        "compatibility_zero": {
            generator["generator_id"]: generator["compatibility_zero"] for generator in expanded["generators"]
        },
    }


def build_basis_json(basis: dict[str, Any], expanded: dict[str, Any], ctx: dict[str, Any]) -> dict[str, Any]:
    return {
        "group_number": GROUP_NUMBER,
        "basis_construction_method": "exact integer subset search in the BS-basis coefficient lattice",
        "basis_column_order": basis["basis_ids"],
        "unknown_ordering": ctx["basis_raw"]["unknown_ordering"],
        "basis_vectors": basis["basis_vectors"],
        "basis_bs_coefficients": basis["basis_coefficients"],
        "rank_z": basis["rank_z"],
        "candidate_to_basis_integer_relations": basis["candidate_to_basis_relations"],
        "raw_candidate_count": len(expanded["column_order"]),
    }


def build_package_readme() -> str:
    lines = [
        "# Review Package: 10.4.1.31 Expanded AI Candidates",
        "",
        "## Scope",
        "",
        "- group: `10.4.1.31`",
        "- stage: expanded AI candidate lattice for a single group",
        "",
        "## Known Premise",
        "",
        "- The k-space line/plane formalism is already accepted.",
        "- The with-planes BS basis is the audited 8-dimensional one.",
        "- The `swyckoff_r.py <-> SSGReps.py` bridge is already validated.",
        "- The earlier minimal prototype (`c_trivial`, `f_trivial`) already embeds in the audited BS lattice.",
        "",
        "## New Content",
        "",
        "- `single_group_local_rep_census_audit.md`: family tiering and inclusion/exclusion logic",
        "- `single_group_local_rep_census_summary.json`: compact census summary",
        "- `single_group_ai_expanded_candidates.json`: 15 successful atomic candidate generators",
        "- `single_group_ai_expanded_matrix.json`: raw candidate matrix aligned with the 31-dimensional unknown ordering",
        "- `single_group_ai_expanded_basis.json`: a reduced 6-generator exact integer basis for the raw candidate lattice",
        "- `single_group_bs_vs_ai_expanded_summary.json`: larger BS-vs-AI comparison against the audited BS lattice",
        "- `debug_single_group_ai_expanded.py`: single-group reproduction script",
        "",
        "## Interpretation",
        "",
        "- This package does build an expanded AI candidate lattice for `10.4.1.31`.",
        "- It still does not claim a full AI lattice or a final topological classification.",
        "- The present gap is tied to the not-yet-implemented magnetic local coreps on the antiunitary families.",
        "",
        "## Suggested Review Order",
        "",
        "1. `audit/single_group_local_rep_census_audit.md`",
        "2. `audit/single_group_local_rep_census_summary.json`",
        "3. `ai/single_group_ai_expanded_candidates.json`",
        "4. `ai/single_group_ai_expanded_basis.json`",
        "5. `ai/single_group_bs_vs_ai_expanded_summary.json`",
    ]
    return "\n".join(lines)


def reset_dir(path: Path) -> None:
    if path.exists():
        for child in sorted(path.rglob("*"), reverse=True):
            if child.is_file() or child.is_symlink():
                child.unlink()
            elif child.is_dir():
                child.rmdir()
        path.rmdir()
    path.mkdir(parents=True, exist_ok=True)


def build_package() -> None:
    reset_dir(PACKAGE_DIR)

    mapping = {
        "audit/single_group_local_rep_census_audit.md": LOCAL_REP_CENSUS_AUDIT_MD,
        "audit/single_group_local_rep_census_summary.json": LOCAL_REP_CENSUS_SUMMARY_JSON,
        "ai/single_group_ai_expanded_candidates.json": AI_EXPANDED_CANDIDATES_JSON,
        "ai/single_group_ai_expanded_matrix.json": AI_EXPANDED_MATRIX_JSON,
        "ai/single_group_ai_expanded_basis.json": AI_EXPANDED_BASIS_JSON,
        "ai/single_group_bs_vs_ai_expanded_summary.json": BS_VS_AI_EXPANDED_SUMMARY_JSON,
        "scripts/debug_single_group_ai_expanded.py": ROOT / "debug_single_group_ai_expanded.py",
        "dependencies/swyckoff_r.py": ROOT / "swyckoff_r.py",
        "dependencies/swyckoff_k.py": ROOT / "swyckoff_k.py",
        "dependencies/SSGReps/SSGReps.py": ROOT / "SSGReps" / "SSGReps" / "SSGReps.py",
        "dependencies/SSGReps/rep_utils.py": ROOT / "SSGReps" / "SSGReps" / "rep_utils.py",
        "dependencies/SSGReps/SG_utils.py": ROOT / "SSGReps" / "SSGReps" / "SG_utils.py",
    }
    mapping.update(BACKGROUND_CONTEXT)

    for relative, source in mapping.items():
        destination = PACKAGE_DIR / relative
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_bytes(source.read_bytes())

    write_text(PACKAGE_DIR / "README.md", build_package_readme())

    if PACKAGE_TARBALL.exists():
        PACKAGE_TARBALL.unlink()
    with tarfile.open(PACKAGE_TARBALL, "w:gz") as tar:
        tar.add(PACKAGE_DIR, arcname=PACKAGE_NAME)


def generate_outputs() -> dict[str, Any]:
    ctx = bridge.load_context()
    census = build_local_rep_census(ctx)
    expanded = build_expanded_candidates(ctx)
    basis = choose_integer_basis(expanded)
    bs_vs_ai = build_bs_vs_ai_expanded_summary(expanded, basis, ctx)

    write_text(LOCAL_REP_CENSUS_AUDIT_MD, build_local_rep_census_md(census, ctx))
    write_json(LOCAL_REP_CENSUS_SUMMARY_JSON, census)
    write_json(AI_EXPANDED_CANDIDATES_JSON, build_candidates_json(expanded, ctx))
    write_json(AI_EXPANDED_MATRIX_JSON, build_matrix_json(expanded, basis, ctx))
    write_json(AI_EXPANDED_BASIS_JSON, build_basis_json(basis, expanded, ctx))
    write_json(BS_VS_AI_EXPANDED_SUMMARY_JSON, bs_vs_ai)
    build_package()

    return {
        "census": census,
        "expanded": expanded,
        "basis": basis,
        "bs_vs_ai": bs_vs_ai,
    }


def validate_outputs() -> None:
    required_paths = [
        LOCAL_REP_CENSUS_AUDIT_MD,
        LOCAL_REP_CENSUS_SUMMARY_JSON,
        AI_EXPANDED_CANDIDATES_JSON,
        AI_EXPANDED_MATRIX_JSON,
        AI_EXPANDED_BASIS_JSON,
        BS_VS_AI_EXPANDED_SUMMARY_JSON,
        PACKAGE_TARBALL,
    ]
    for path in required_paths:
        if not path.exists():
            raise ValueError(f"missing required artifact: {path}")

    census = load_json(LOCAL_REP_CENSUS_SUMMARY_JSON)
    if census["group_number"] != GROUP_NUMBER:
        raise ValueError("census group number mismatch")
    if not census["can_build_expanded_ai_candidates"]:
        raise ValueError("expanded candidate build was not reported as possible")

    matrix = load_json(AI_EXPANDED_MATRIX_JSON)
    if matrix["rank_z"] != 6:
        raise ValueError("unexpected expanded AI rank")

    basis = load_json(AI_EXPANDED_BASIS_JSON)
    if len(basis["basis_column_order"]) != 6:
        raise ValueError("unexpected expanded basis size")

    bs_vs_ai = load_json(BS_VS_AI_EXPANDED_SUMMARY_JSON)
    if bs_vs_ai["rank_BS_with_planes"] != 8:
        raise ValueError("unexpected BS rank")
    if bs_vs_ai["rank_AI_expanded"] != 6:
        raise ValueError("unexpected expanded AI rank in summary")
    if not bs_vs_ai["AI_expanded_in_BS"]:
        raise ValueError("expanded AI was not reported as embedded in BS")

    expected_members = {
        f"{PACKAGE_NAME}/README.md",
        f"{PACKAGE_NAME}/audit/single_group_local_rep_census_audit.md",
        f"{PACKAGE_NAME}/audit/single_group_local_rep_census_summary.json",
        f"{PACKAGE_NAME}/ai/single_group_ai_expanded_candidates.json",
        f"{PACKAGE_NAME}/ai/single_group_ai_expanded_matrix.json",
        f"{PACKAGE_NAME}/ai/single_group_ai_expanded_basis.json",
        f"{PACKAGE_NAME}/ai/single_group_bs_vs_ai_expanded_summary.json",
        f"{PACKAGE_NAME}/scripts/debug_single_group_ai_expanded.py",
    }
    with tarfile.open(PACKAGE_TARBALL, "r:gz") as tar:
        members = {member.name for member in tar.getmembers()}
    missing = sorted(expected_members - members)
    if missing:
        raise ValueError(f"package is missing expected members: {missing}")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Build the expanded single-group AI candidate lattice for 10.4.1.31."
    )
    parser.add_argument("--validate", action="store_true", help="Validate previously generated outputs and exit.")
    args = parser.parse_args()

    if args.validate:
        validate_outputs()
        print("validation_ok")
        return 0

    result = generate_outputs()
    print(json.dumps(result["bs_vs_ai"], indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
