#!/data/home/szhang/anaconda3/bin/python3
import os, sys
import argparse

parser = argparse.ArgumentParser(description='Process command line arguments')

parser.add_argument('-og', type=int, help='Value for OG', required=True)
parser.add_argument('-sg', type=int, help='Value for SG', required=True)
parser.add_argument('-mode', type=int, help='Value for MODE: 1--solve_CR, 2--cal_SI', required=True)

bilbaodata = '/data/home/szhang/soft_sz/topmat_src/BilBaoData/'
depend_path = '/data/home/szhang/soft_sz/topmat_src/'

args = parser.parse_args()
if args.mode == 1:
    todo = 'solve_CR'
elif args.mode == 2:
    todo = 'cal_SI'
else:
    print("ERROR: Wrong Mode!!!")
    sys.exit()
    
sgnum = args.sg
ognum = args.og
# check the format of PPOSCAR
if todo == 'POS2MSG':
    msginfo = dict()
    msgtype = dict()
    f = open(bilbaodata+'msginfo', 'r')
    for i in range(1651):
        tmp = f.readline().split()
        msginfo_og, msginfo_sg, msginfo_type = int(tmp[0]), int(tmp[4].split('.')[0]), int(tmp[1])
        if msginfo_sg not in msginfo.keys():
           msginfo[msginfo_sg] = []
        msginfo[msginfo_sg].append(msginfo_og)
        msgtype[msginfo_og] = msginfo_type
    f.close()
    if sgnum <= 1 or sgnum > 230: 
        print("The space group number is out of range.")
        sys.exit()

    try:
        f = open('PPOSCAR','r')
        f.readline()
        scale = float(f.readline())
        for i in range(3):
            lattvec = list(map(float, f.readline().strip().split()))
            assert len(lattvec) == 3
        f.readline()
        num_atom = sum(list(map(int, f.readline().strip().split()))) 
        f.readline()
        for i in range(num_atom):
            atompos = list(map(float, f.readline().strip().split()))
            assert len(atompos) == 3
            
    except BaseException:
        print("Error when reading PPOSCAR")
        sys.exit()
    f.close()

if todo == 'solve_CR' or todo == 'cal_SI':
    if ognum <= 1 or ognum > 1651: 
        print("The OG magnetic space group number is out of range.")
        sys.exit()
    # check the format of PPOSCAR
    try:
        collect = []
        f = open('tqc.data','r')
        sg, numk, numb = list(map(int, f.readline().strip().split())) 
        for i in range(numk):
            tmp = f.readline().strip()
            assert '?' not in tmp
            brdata = list(map(int, tmp.split()))
            assert len(brdata) > 1
            assert len(brdata) <= (numb + 1)
            collect.append(brdata)
    except BaseException:
        print("Error when reading tqc.data")
        sys.exit()
    f.close()

    # check soc
    ref = dict()
    kname = []
    kfile = open(bilbaodata + 'kvec_list_A.txt','r') 
    for i in range(230):
        content = kfile.readline().strip().split()
        nowsg, totk = list(map(int, content))
        if sg != nowsg:
            for ik in range(totk):
                kfile.readline()
        else:
            for ik in range(totk):
                tmp0 = kfile.readline().strip().split()
                tmp = list(map(int, tmp0[0:4]))
                ref[tmp[0]] = tuple(tmp[1:4])
                kname.append(tmp0[5])
            break
	
    for ik in range(numk):
        if collect[ik][0] < 0:
            absk = abs(collect[ik][0])
            abskname = kname[absk-1]
            knameA = abskname+'A'
            kaindex = kname.index(knameA) + 1
            collect[ik][0] = kaindex 

    for brdata in collect:
        nowref = ref[brdata[0]]
        if any([rep > nowref[0] for rep in brdata[1:]]):
            print("Error when reading tqc.data 1")
            sys.exit()
        if all([rep <= nowref[1] for rep in brdata[1:]]):
            soc = 0
        elif all([rep > nowref[1] for rep in brdata[1:]]):
            soc = 1
        else:
            print("Error when reading tqc.data 2")
            sys.exit()
    kfile.close()

#------------------------------------------------------------
#print()
#print ("<h1> your PPOSCAR and fort.67 have been submitted </h1>" )

if todo == 'POS2MSG':
    os.system('chmod 777 PPOSCAR')
    os.system('bash '+depend_path+'work_msginput.sh {:>5d} {:>5d}'.format(sgnum, ognum))

    f = open('posout', 'r')
    try:
        posout_sg = int(f.readline().strip().split()[0])
    except BaseException:
        print("Error, please confirm that the input structure is generated by phonopy.")
        sys.exit()
    f.close()
    if posout_sg != sgnum:
        print("Error, the input space group number do not match with the structure.")
        print("The space group number is {:4d}.".format(posout_sg))
        sys.exit()
    if ognum not in msginfo[sgnum]: 
        print("The OG magnetic space group number do not match with the given space group number.")
        print("Possible OG magnetic space group numbers are given below:")
        for og in msginfo[sgnum]:
            print("{:5d}, type {:2d}".format(og, msgtype[og]))
        sys.exit()

    print("POSCAR_msg:")
    f = open('POSCARm','r')
    poscarm = f.readlines()
    f.close()
    for line in poscarm:
        #linetmp = line.replace(' ','&nbsp;')
        print("{:s}".format(line))
    print("INCAR:")
    print("LSORBIT = T")
    print("LNONCOLLINEAR = T")
    print("SAXIS = 0 0 1")
    f = open('INCARm','r')
    incarm = f.readlines()
    f.close()
    for line in incarm:
        #linetmp = line.replace(' ','&nbsp;')
        print("{:s}".format(line))

    print("KPOINTS:")
    f = open('KPOINTS.hsp','r')
    incarm = f.readlines()
    f.close()
    for line in incarm:
        #linetmp = line.replace(' ','&nbsp;')
        print("{:s}".format(line))

elif todo == 'cal_SI':
    if soc == 0:
        print("Now we do not support the calculation without spin-orbit coupling.")
        sys.exit()
    elif soc == 1:
        print("The input data is calculated with spin-orbit coupling.")
        os.system('bash '+depend_path+'work_ind.sh 1 '+str(ognum))
    f = open('indout','r')
    data = f.readlines()
    f.close()
    for line in data:
        #linetmp = line.replace(' ','&nbsp;')
        print("{:s}".format(line))

elif todo == 'solve_CR':
    if soc == 0:
        print("Now we do not support the calculation without spin-orbit coupling.")
        sys.exit()
        #print("<b><font face='courier new'>The input data is calculated without spin-orbit coupling.</b>")
        #print("<br>")
        #os.system('bash work_cr.sh 0 '+str(ognum))
    elif soc == 1:
        print("The input data is calculated with spin-orbit coupling.")
        os.system('bash '+depend_path+'work_cr.sh 1 '+str(ognum))
    f = open('crout','r')
    data = f.readlines()
    f.close()
    for line in data:
        #linetmp = line.replace(' ','&nbsp;')
        print("{:s}".format(line))
